version: '3.8'

services:
  technical-api:
    image: technicalapp-api:0.0.1-SNAPSHOT
    container_name: technicalapp
    volumes:
      - ./build/libs/technical-app-0.0.1-SNAPSHOT.jar:/app/api/technical-app.jar
    ports:
      - '8080:8080'
      - '5005:5005'
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:13-alpine
    container_name: technicalapp_db
    environment:
      POSTGRES_DB: $DS_DB_NAME
      POSTGRES_USER: $DS_USERNAME
      POSTGRES_PASSWORD: $DS_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - techapp_vol:/var/lib/postgresql/data

volumes:
  techapp_vol:
