version: '3'

services:
  technical-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: technical_app/api
    container_name: technicalapp_api
    ports:
      - '8080:8080'
      - '5005:5005'
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:13-alpine
    container_name: technicalapp_db
    environment:
      POSTGRES_DB: techapp
      POSTGRES_USER: techapp
      POSTGRES_PASSWORD: techapp
    ports:
      - '5432:5432'
    volumes:
      - techapp_vol:/var/lib/postgresql/data

volumes:
  techapp_vol:
