spring:
  datasource:
    url: jdbc:postgresql://db:5432/techapp
    username: techapp
    password: techapp
    name: techappdatasource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: techappool
      connection-test-query: select 1;
      maximum-pol-size: 10
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: false
  devtools:
    remote:
      secret: mysecret
  banner:
    output:
      ansi:
        enabled: always
