version: 0.2

phases:
  install:
    runtime-versions:
      java:  openjdk11
    commands:
      - echo Installing openjdk11...
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase...
  build:
    commands:
     - echo Build started
     - ./gradlew build
  post_build:
    commands:
      - echo Build completed
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
